export const SliderData = [
  { image: require('../../images/C4_Images_Listen_1.jpeg') },
  { image: require('../../images/C4_Images_Listen_2.jpeg') },
  { image: require('../../images/C4_Images_Listen_3.jpeg') },
  { image: require('../../images/C4_Images_Listen_4.jpeg') },
  { image: require('../../images/C4_Images_Video_2.jpeg') },
  { image: require('../../images/C4_Images_Video_3.jpeg') },
  { image: require('../../images/C4_Images_Video_4.jpeg') },
  { image: require('../../images/C4_Images_Video_5.jpeg') },
  { image: require('../../images/C4_Images_Video_6.jpeg') },
  { image: require('../../images/C4_Images_Video_7.jpeg') },
  { image: require('../../images/C4_Images_Video_8.jpeg') },
  { image: require('../../images/NEEO_Lifestyle_2.jpg') },
  { image: require('../../images/NEEO_Lifestyle_7.jpg') },
  { image: require('../../images/NEEO_Lifestyle_11.jpg') },
];
